catalogMode: prefer

shamefullyHoist: true
shellEmulator: true

supportedArchitectures:
  cpu: [x64, arm64]
  os: [linux, darwin, win32]

trustPolicy: no-downgrade

packages:
  - apps/*
  - packages/*

catalogs:
  dev:
    '@antfu/eslint-config': ^7.7.3
    '@commitlint/cli': ^20.5.3
    '@commitlint/config-conventional': ^20.5.3
    '@iconify-json/circle-flags': ^1.2.10
    '@iconify-json/fluent-emoji-flat': ^1.2.5
    '@iconify-json/lucide': ^1.2.108
    '@iconify-json/simple-icons': ^1.2.83
    '@nuxt/devtools': ^3.2.4
    '@nuxtjs/i18n': ^10.3.0
    bumpp: ^11.1.0
    eslint: ^9.39.4
    husky: ^9.1.7
    lint-staged: ^16.4.0
    nuxt: ^4.4.2
    nuxt-auth-utils: ^0.5.29
    tailwindcss-motion: ^1.1.1
    typescript: ^5.9.3
    unbuild: ^3.6.1
    vite: ^7.3.1
    vue-tsc: ^3.3.1
  integrations:
    '@date-fns/tz': ^1.4.1
    '@neoconfetti/vue': ^2.2.1
    '@nuxt/ui': ^4.7.1
    '@paralleldrive/cuid2': ^3.3.0
    '@pinia/nuxt': ^0.11.3
    '@vueuse/core': ^14.3.0
    '@vueuse/nuxt': ^14.3.0
    libphonenumber-js: ^1.13.2
    pinia: ^3.0.4
    zod: ^4.4.3
  test:
    '@playwright/test': ^1.60.0
    '@vitest/browser-playwright': ^4.1.7
    '@vitest/coverage-v8': ^4.1.7
    playwright: ^1.60.0
    vitest: ^4.1.7
  types:
    '@types/node': ^25.9.1

autoInstallPeers: true
