packages:
  - apps/*
  - packages/*

catalog:
  '@antfu/eslint-config': ^6.0.0
  '@commitlint/cli': ^20.1.0
  '@commitlint/config-conventional': ^20.0.0
  '@date-fns/tz': ^1.4.1
  '@iconify-json/circle-flags': ^1.2.10
  '@iconify-json/fluent-emoji-flat': ^1.2.5
  '@iconify-json/lucide': ^1.2.70
  '@iconify-json/simple-icons': ^1.2.55
  '@neoconfetti/vue': ^2.2.1
  '@nuxt/devtools': ^2.6.5
  '@nuxt/image': ^1.11.0
  '@nuxt/ui': ^4.0.1
  '@nuxtjs/i18n': ^10.1.1
  '@paralleldrive/cuid2': ^3.1.0
  '@pinia/nuxt': ^0.11.2
  '@tailwindcss/typography': ^0.5.19
  '@types/node': ^24.9.1
  '@types/pg': ^8.15.4
  '@vitejs/plugin-vue': ^6.0.1
  '@vitest/browser': ^3.2.4
  '@vitest/coverage-v8': ^3.2.4
  '@vueuse/core': ^14.0.0
  '@vueuse/nuxt': ^14.0.0
  arktype: ^2.1.20
  aws4fetch: ^1.0.20
  bumpp: ^10.3.1
  dotenv: ^17.2.3
  drizzle-cuid2: ^2.0.0
  drizzle-kit: ^0.31.1
  drizzle-orm: ^0.44.2
  eslint: ^9.38.0
  husky: ^9.1.7
  ioredis: ^5.8.2
  libphonenumber-js: ^1.12.24
  lint-staged: ^16.2.5
  nuxt: ^4.1.3
  nuxt-auth-utils: ^0.5.25
  nuxt-tiptap-editor: ^2.3.1
  nuxt-zod-i18n: ^1.12.1
  pg: ^8.16.0
  pinia: ^3.0.3
  playwright: ^1.56.1
  sharp: ^0.34.2
  typescript: ^5.9.3
  unbuild: ^3.6.1
  vite: ^7.1.11
  vite-tsconfig-paths: ^5.1.4
  vitest: ^3.2.4
  vitest-browser-vue: ^1.1.0
  vue-tsc: ^3.1.1
  zod: ^3.25.57

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - msw
  - vue-demi

onlyBuiltDependencies:
  - sharp

supportedArchitectures:
  cpu: [x64, arm64]
  os: [linux, darwin, win32]

autoInstallPeers: true
shamefullyHoist: true
