catalogMode: prefer

shamefullyHoist: true
shellEmulator: true

supportedArchitectures:
  cpu: [x64, arm64]
  os: [linux, darwin, win32]

trustPolicy: no-downgrade

packages:
  - apps/*
  - packages/*

catalogs:
  dev:
    '@antfu/eslint-config': ^7.6.1
    '@commitlint/cli': ^20.4.2
    '@commitlint/config-conventional': ^20.4.2
    '@iconify-json/circle-flags': ^1.2.10
    '@iconify-json/fluent-emoji-flat': ^1.2.5
    '@iconify-json/lucide': ^1.2.95
    '@iconify-json/simple-icons': ^1.2.72
    '@nuxt/devtools': ^3.2.2
    '@nuxtjs/i18n': ^10.2.3
    '@tailwindcss/typography': ^0.5.19
    bumpp: ^10.4.1
    eslint: ^9.39.3
    husky: ^9.1.7
    lint-staged: ^16.3.1
    nuxt: ^4.3.1
    nuxt-auth-utils: ^0.5.29
    tailwindcss-motion: ^1.1.1
    typescript: ^5.9.3
    unbuild: ^3.6.1
    vite: ^7.3.1
    vue-tsc: ^3.2.5
  integrations:
    '@date-fns/tz': ^1.4.1
    '@neoconfetti/vue': ^2.2.1
    '@nuxt/ui': ^4.5.0
    '@paralleldrive/cuid2': 2.3.1
    '@pinia/nuxt': ^0.11.3
    '@vueuse/core': ^14.2.1
    '@vueuse/nuxt': ^14.2.1
    libphonenumber-js: ^1.12.38
    pinia: ^3.0.4
    zod: ^4.3.6
  test:
    '@vitest/browser-playwright': ^4.0.18
    '@vitest/coverage-v8': ^4.0.18
    playwright: ^1.58.2
    vitest: ^4.0.18
  types:
    '@types/node': ^25.3.3

autoInstallPeers: true
