packages:
  - apps/*
  - packages/*

catalogs:
  dev:
    '@antfu/eslint-config': ^6.0.0
    '@commitlint/cli': ^20.1.0
    '@commitlint/config-conventional': ^20.0.0
    '@iconify-json/circle-flags': ^1.2.10
    '@iconify-json/fluent-emoji-flat': ^1.2.5
    '@iconify-json/lucide': ^1.2.71
    '@iconify-json/simple-icons': ^1.2.55
    '@nuxt/devtools': ^2.6.5
    '@nuxt/image': ^1.11.0
    '@nuxtjs/i18n': ^10.1.1
    '@tailwindcss/typography': ^0.5.19
    bumpp: ^10.3.1
    eslint: ^9.38.0
    husky: ^9.1.7
    lint-staged: ^16.2.6
    nuxt: ^4.2.0
    nuxt-auth-utils: ^0.5.25
    typescript: ^5.9.3
    unbuild: ^3.6.1
    vite: ^7.1.12
    vue-tsc: ^3.1.2
  integrations:
    '@date-fns/tz': ^1.4.1
    '@neoconfetti/vue': ^2.2.1
    '@nuxt/ui': ^4.1.0
    '@paralleldrive/cuid2': 2.2.2
    '@pinia/nuxt': ^0.11.2
    '@vueuse/core': 13.9.0
    '@vueuse/nuxt': 13.9.0
    arktype: ^2.1.20
    aws4fetch: ^1.0.20
    ioredis: ^5.8.2
    libphonenumber-js: ^1.12.25
    nuxt-tiptap-editor: ^2.3.1
    nuxt-zod-i18n: ^1.12.1
    pinia: ^3.0.3
    sharp: ^0.34.4
    zod: ^3.25.57
  test:
    '@vitest/browser': ^4.0.16
    '@vitest/coverage-v8': ^4.0.16
    playwright: ^1.56.1
    vitest: ^4.0.16
    vitest-browser-vue: ^1.1.0
  types:
    '@types/node': ^24.9.1

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - msw
  - vue-demi

onlyBuiltDependencies:
  - sharp

supportedArchitectures:
  cpu: [x64, arm64]
  os: [linux, darwin, win32]

autoInstallPeers: true
shamefullyHoist: true
