services:
  db:
    image: redis:7
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    command:
      - --protected-mode
      - no
      - --appendonly
      - no
      - --save
      - '300'
      - '1'

volumes:
  redis_data:
