name: CI

on:
  push:
    paths-ignore:
      - "*.md"
      - "docker/**"
      - ".github/**"
      - "!.github/workflows/ci.yml"
    branches:
      - main
  pull_request:
    paths-ignore:
      - "*.md"
      - "docker/**"
      - ".github/**"
      - "!.github/workflows/ci.yml"
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: PNPM
        uses: pnpm/action-setup@v5
        with:
          run_install: false

      - name: Node
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build packages
        run: pnpm --filter @nextorders/food-schema run build

      - name: ESLint
        run: pnpm run lint

      - name: Typecheck
        run: pnpm run typecheck

      - name: Test
        run: pnpm run test

      - name: Install Playwright browsers
        run: pnpm playwright install --with-deps chromium

      - name: E2E tests
        run: pnpm run test:e2e

      - name: Build
        run: pnpm run build
